export enum ErrorCodes {

  // Airport
  AIRPORT_NOT_FOUND = '100',
  AIRPORT_NEW_WITH_ID = '101',
  AIRPORT_IATA_NOT_FOUND = '102',
  AIRPORT_NO_COORDINATES = '103',
  AIRPORT_IATA_DUPLICATE = '104',
  AIRPORT_ICAO_DUPLICATE = '105',

  // Airport Observation
  AIRPORT_OBSERVATION_NOT_FOUND = '110',
  AIRPORT_OBSERVATION_NEW_WITH_ID = '111',

  // Airport Operator
  AIRPORT_OPERATOR_NOT_FOUND = '120',
  AIRPORT_OPERATOR_NEW_WITH_ID = '121',

  // Region
  REGION_NOT_FOUND = '130',
  REGION_NEW_WITH_ID = '131',
  REGION_AIRPORT_NOT_FOUND = '132',

  // Runway
  RUNWAY_NOT_FOUND = '140',
  RUNWAY_NEW_WITH_ID = '141',

  // Runway
  TERMINAL_NOT_FOUND = '150',
  TERMINAL_NEW_WITH_ID = '151',

  // File
  FILE_NOT_FOUND = '160',
  FILE_NEW_WITH_ID = '161',

  // Taxes
  TAX_NOT_FOUND = '170',
  TAX_ROUTE_BALEARIC_NOT_FOUND = '171',

  // City
  CITY_NOT_FOUND = '180',

  // Contract Cancel fee
  CONTRACT_CANCEL_FEE_NOT_FOUND = '190',
  CONTRACT_CANCEL_FEE_NEW_WITH_ID = '191',

  // Contract Condition
  CONTRACT_CONDITION_NOT_FOUND = '200',
  CONTRACT_CONDITION_NEW_WITH_ID = '201',
  CONTRACT_CONDITION_NOT_FOUND_MULTIPLE = '202',

  // Contract
  CONTRACT_NOT_FOUND = '210',
  CONTRACT_NEW_WITH_ID = '211',
  CONTRACT_GENERATION_FAIL = '212',
  CONTRACT_SIGNED_MODIFICATION = '213',

  // Contract Configuration
  CONTRACT_CONFIGURATION_NOT_FOUND = '220',
  CONTRACT_CONFIGURATION_NEW_WITH_ID = '221',
  CONTRACT_CONFIGURATION_MISMATCH = '222',

  // Contract Payment Condition
  CONTRACT_PAYMENT_CONDITION_NOT_FOUND = '230',
  CONTRACT_PAYMENT_CONDITION_NEW_WITH_ID = '231',

  // Contract Line
  CONTRACT_LINE_NOT_FOUND = '240',
  CONTRACT_LINE_CONTRACT_MISMATCH = '241',

  // Contribution
  CONTRIBUTION_NOT_FOUND = '250',
  CONTRIBUTION_NEW_WITH_ID = '251',
  CONTRIBUTION_ROUTE_NOT_FOUND = '252',
  CONTRIBUTION_LINE_NOT_FOUND = '253',
  CONTRIBUTION_LINE_CONTRIBUTION_MISMATCH = '254',
  CONTRIBUTION_LINE_ROUTE_MISMATCH = '255',
  CONTRIBUTION_LINE_SALE_LINE_NOT_FOUND = '256',
  CONTRIBUTION_WITH_NO_FLIGHTS = '257',

  // Route
  ROUTE_NOT_FOUND = '260',
  ROUTE_NEW_WITH_ID = '261',
  ROUTE_WITH_NO_ROTATIONS = '262',
  ROUTE_FIRST_FLIGHT_NOT_FOUND = '263',
  ROUTE_LAST_FLIGHT_NOT_FOUND = '264',
  ROUTE_WITH_NO_FLIGHTS = '265',
  ROUTE_WITH_CONTRIBUTIONS = '266',
  ROUTE_WITH_NO_FREQ_DAYS = '267',
  ROUTE_ROTATION_NOT_FOUND = '268',
  ROUTE_DATES_ERROR = '269',

  // Country
  COUNTRY_NOT_FOUND = '270',

  // Client
  CLIENT_NOT_FOUND = '280',
  CLIENT_NEW_WITH_ID = '281',

  // Contact
  CONTACT_NOT_FOUND = '290',
  CONTACT_NEW_WITH_ID = '291',

  // File Additional Data
  FILE_ADDITIONAL_DATA_NOT_FOUND = '300',
  FILE_ADDITIONAL_DATA_NEW_WITH_ID = '301',

  // File Status
  FILE_STATUS_NOT_FOUND = '300',
  FILE_STATUS_NEW_WITH_ID = '301',
  FILE_STATUS_CODE_NOT_FOUND = '302',

  // Provider
  PROVIDER_NOT_FOUND = '310',
  PROVIDER_NEW_WITH_ID = '311',

  // Aircraft Base
  AIRCRAFT_BASE_NOT_FOUND = '320',
  AIRCRAFT_BASE_NEW_WITH_ID = '321',

  // Aircraft
  AIRCRAFT_NOT_FOUND = '330',
  AIRCRAFT_NEW_WITH_ID = '331',

  // Aircraft Category
  AIRCRAFT_CATEGORY_NOT_FOUND = '340',
  AIRCRAFT_CATEGORY_NEW_WITH_ID = '341',
  AIRCRAFT_SUBCATEGORY_NOT_FOUND = '342',
  AIRCRAFT_SUBCATEGORY_NEW_WITH_ID = '343',

  // Aircraft Category
  AIRCRAFT_OBSERVATION_NOT_FOUND = '350',
  AIRCRAFT_OBSERVATION_NEW_WITH_ID = '351',

  // Flight
  FLIGHT_NOT_FOUND = '360',
  FLIGHT_NEW_WITH_ID = '361',
  FLIGHT_GET_ROUTE_ERROR = '362',

  // Aircraft Type
  AIRCRAFT_TYPE_NOT_FOUND = '370',
  AIRCRAFT_TYPE_NEW_WITH_ID = '371',
  AIRCRAFT_TYPE_NO_FLIGHT_RANGE = '372',

  // Aircraft Type Observation
  AIRCRAFT_TYPE_OBSERVATION_NOT_FOUND = '380',
  AIRCRAFT_TYPE_OBSERVATION_NEW_WITH_ID = '381',

  // Aircraft Type Average Speed
  AIRCRAFT_TYPE_AVG_SPEED_NOT_FOUND = '390',
  AIRCRAFT_TYPE_AVG_SPEED_NEW_WITH_ID = '391',

  // Flight Service
  FLIGHT_SERVICE_NOT_FOUND = '400',
  FLIGHT_SERVICE_NEW_WITH_ID = '401',
  FLIGHT_SERVICE_NO_FLIGHT_IDS = '402',

  // Service
  SERVICE_NOT_FOUND = '410',
  SERVICE_NEW_WITH_ID = '411',

  // Operator
  OPERATOR_NOT_FOUND = '420',
  OPERATOR_NEW_WITH_ID = '421',

  // Operator Comment
  OPERATOR_COMMENT_NOT_FOUND = '430',

  // Role
  ROLE_NOT_FOUND = '440',
  ROLE_NEW_WITH_ID = '441',

  // Task
  TASK_NOT_FOUND = '450',
  TASK_NEW_WITH_ID = '451',

  // Screen
  SCREEN_NOT_FOUND = '460',
  SCREEN_NEW_WITH_ID = '461',

  // User
  USER_NOT_FOUND = '470',
  USER_TOKEN_NOT_FOUND = '471',
  USER_SYSTEM_NOT_FOUND = '472',
  USER_USERNAME_NOT_FOUND = '473',
  USER_FOR_MENU_NOT_FOUND = '474',

  // Conversion
  CONVERSION_FLIGHT_RANGE_ERROR = '480',

  // Filter
  FILTER_PARAMS_INVALID_OPERATOR = '490',
  FILTER_PARAMS_INVALID_PARAMS = '491',

  // State
  STATE_FILE_STATATUS_NOT_FOUND = '500',
  STATE_CHANGE_FILE = '501',
  STATE_CHANGE_CONTRIBUTION = '502',
  STATE_CHANGE_CONTRACT = '503',
  STATE_CHANGE_ROUTE = '504'
}

export function getErrorTranslationLabel(enumValue: number | string): string {
  return Object.keys(ErrorCodes).find((x) => ErrorCodes[x] == enumValue);
}
