export enum OperatorEnum {
  EQUALS = 'EQUALS',
  GREATER = 'GREATER',
  LOWER = 'LOWER',
  GREATER_OR_EQ = 'GREATER_OR_EQ',
  LOWER_OR_EQ = 'LOWER_OR_EQ',
  NOT_EQUALS = 'NOT_EQUALS',
  IS_NULL = 'IS_NULL',
  IS_NOT_NULL = 'IS_NOT_NULL',
  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  IN = 'IN',
  EMPTY = ''
}
